// This file is auto-generated by Uca. Do not edit.
// To regenerate, run: uca tidy

package context

import "github.com/pocketbase/pocketbase/core"

type RequestEvent = core.RequestEvent
type App = core.App
type Collection = core.Collection
type Record = core.Record

func NewRecord(collection *core.Collection) *core.Record {
	return core.NewRecord(collection)
}
