# This file is auto-generated by Uca. Do not edit.
# To regenerate, run: uca tidy

from litellm import completion as _completion
import os


class Agent:
    def __init__(self, model_id: str, api_key: str = None, api_base: str = None):
        self.model_id = model_id
        self.api_key = api_key or os.environ.get("GITHUB_PAT_TOKEN", "")
        self.api_base = api_base or "https://models.inference.ai.azure.com"

    def run(self, message: str, timeout: int = 30) -> str:
        response = _completion(
            model=self.model_id,
            messages=[{"role": "user", "content": message}],
            api_key=self.api_key,
            api_base=self.api_base,
            timeout=timeout
        )
        return response.choices[0].message.content
