# This file is auto-generated by Uca. Do not edit.
# To regenerate, run: uca tidy

from litellm import completion as _completion
import os
import json
import inspect
import sys
import atexit

class Message:
    def __str__(self):
        return "{{UCA_MESSAGE_PLACEHOLDER}}"
    def __repr__(self):
        return "{{UCA_MESSAGE_PLACEHOLDER}}"

Message = Message()

_main_agent = None

class Agent:
    def __init__(self, model: str = None, tools: list = None):
        global _main_agent
        # Determine name from the calling file's name
        frame = inspect.stack()[1]
        module = inspect.getmodule(frame[0])
        
        if module and module.__file__:
            self.name = os.path.splitext(os.path.basename(module.__file__))[0]
            if module.__name__ == "__main__":
                _main_agent = self
        else:
            self.name = "unknown"

        self._model = model
        self._yaml_tools = tools or []
        self._custom_tools = []
        self.prompt = str(Message)
        self.api_key = os.environ.get("GITHUB_PAT_TOKEN", "")
        self.api_base = "https://models.inference.ai.azure.com"

    @property
    def model(self):
        return self._model

    @model.setter
    def model(self, value):
        if self._model != value:
            self._model = value
            print(f"UCA_SYNC:AGENT:{self.name}:MODEL:{value}")

    @property
    def tools(self):
        tools_list = []
        # Add YAML tools (strings)
        for t in self._yaml_tools:
            tools_list.append(t)
        
        # Add custom tools (can be functions or strings or lists of strings)
        for t in self._custom_tools:
            if callable(t):
                tools_list.append(self._function_to_tool(t))
            elif isinstance(t, list):
                tools_list.extend(t)
            else:
                tools_list.append(t)
        return tools_list

    @tools.setter
    def tools(self, value):
        if isinstance(value, list):
            self._custom_tools = value
        else:
            self._custom_tools = [value]

    def _function_to_tool(self, func):
        import inspect
        sig = inspect.signature(func)
        doc = inspect.getdoc(func) or "No description provided."
        
        parameters = {
            "type": "object",
            "properties": {},
            "required": []
        }
        
        for name, param in sig.parameters.items():
            param_type = "string"
            if param.annotation == int: param_type = "integer"
            elif param.annotation == float: param_type = "number"
            elif param.annotation == bool: param_type = "boolean"
            
            parameters["properties"][name] = {
                "type": param_type,
                "description": name
            }
            if param.default == inspect.Parameter.empty:
                parameters["required"].append(name)
                
        return {
            "type": "function",
            "function": {
                "name": func.__name__,
                "description": doc,
                "parameters": parameters
            },
            "uca_callable": func
        }

    def run(self, message: str, timeout: int = 30) -> str:
        final_prompt = self.prompt.replace("{{UCA_MESSAGE_PLACEHOLDER}}", message)

        response = _completion(
            model=self._model,
            messages=[{"role": "user", "content": final_prompt}],
            api_key=self.api_key,
            api_base=self.api_base,
            timeout=timeout
        )
        return response.choices[0].message.content

def _autorun():
    if _main_agent and not sys.argv[0].endswith("server.py"):
        if len(sys.argv) > 1:
            print(_main_agent.run(sys.argv[1]))

atexit.register(_autorun)
