// This file is auto-generated by Uca. Do not edit.
// To regenerate, run: uca tidy

import { defineConfig } from "vitest/config"
import preact from "@preact/preset-vite"
import { resolve } from "path"

export default defineConfig({
  plugins: [preact()],
  test: {
    environment: "jsdom",
    include: ["pages/*.test.tsx"],
  },
  resolve: {
    alias: {
      "uca/types": resolve(__dirname, "types/index.ts"),
      "uca/roles": resolve(__dirname, "roles/index.ts"),
      "uca/ui": resolve(__dirname, "ui/index.ts"),
      "preact/jsx-runtime": resolve(__dirname, "node_modules/preact/jsx-runtime"),
      "preact/jsx-dev-runtime": resolve(__dirname, "node_modules/preact/jsx-runtime"),
      "preact/hooks": resolve(__dirname, "node_modules/preact/hooks"),
      "preact": resolve(__dirname, "node_modules/preact")
    }
  }
})
